import type { Metadata } from 'next'
import { Montserrat, Poppins } from 'next/font/google'
import type { PropsWithChildren } from 'react'
import '../assets/styles/globals.scss'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
})
const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <body
        className={`${montserrat.variable} ${poppins.variable} antialiased font-montserrat bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  )
}
